conference:
  name: "ICML 2025"
  domain: "ICML.cc/2025/Conference"
  invitation: "ICML.cc/2025/Conference/-/Submission"
  output_dir: "icml_2025"

venues:
  - type: "poster"
    venue: "ICML 2025 poster"
  - type: "oral"
    venue: "ICML 2025 oral"
  - type: "spotlight"
    venue: "ICML 2025 spotlightposter"

settings:
  api_base_url: "https://api2.openreview.net/notes"
  limit: 25
  initial_delay: 0.8
  max_delay: 2.0
